# Generated by Django 5.1 on 2024-09-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_uploadedfile_user_uploadedfile_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='owner',
            new_name='user',
        ),
    ]
