# Generated by Django 5.1 on 2024-09-09 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_task_user_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 9, 13, 56, 36, 473342), null=True, verbose_name='Дата'),
        ),
    ]
