# Generated by Django 5.1 on 2024-09-11 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 11, 13, 3, 17, 802180), null=True, verbose_name='Дата'),
        ),
    ]
