# Generated by Django 5.1 on 2024-09-15 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complexity',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 15, 18, 38, 47, 18792), null=True, verbose_name='Дата'),
        ),
    ]
