# Generated by Django 5.1 on 2024-09-17 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_complexity_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complexity',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], max_length=20, null=True, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 17, 5, 51, 6, 421683), null=True, verbose_name='Дата'),
        ),
    ]
