# Generated by Django 5.1 on 2024-09-17 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_complexity_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 17, 6, 11, 22, 508175), null=True, verbose_name='Дата'),
        ),
    ]
